###
GET http://localhost:8080/api/locations/

### get in xml
GET http://localhost:8080/api/locations/
Accept: application/xml

###
POST http://localhost:8080/api/locations
Content-Type: application/json

{
  "name": "Kapolnasnyek",
  "lon": 42.1,
  "lat": 18.7
}

###
PUT http://localhost:8080/api/locations/1
Content-Type: application/json

{
  "name": "Vecses",
  "lon": 88.1,
  "lat": 11.7
}

###
DELETE http://localhost:8080/api/locations/3